# Keep the preload syntax the same
preload = /home/blvck/Pictures/boba01.jpg

# Use the new object block syntax for the wallpaper configuration
wallpaper {
    monitor = eDP-1
    path = /home/blvck/Pictures/boba01.jpg
    fit_mode = cover
}

# Optional: Disable the text splash at the bottom of the screen
splash = false

